# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import whatsapp_pb2 as whatsapp__pb2

GRPC_GENERATED_VERSION = "1.72.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in whatsapp_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class WhatsAppServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMessages = channel.unary_stream(
            "/whatsapp.WhatsAppService/StreamMessages",
            request_serializer=whatsapp__pb2.Empty.SerializeToString,
            response_deserializer=whatsapp__pb2.MessageEvent.FromString,
            _registered_method=True,
        )
        self.StartLogin = channel.unary_unary(
            "/whatsapp.WhatsAppService/StartLogin",
            request_serializer=whatsapp__pb2.Empty.SerializeToString,
            response_deserializer=whatsapp__pb2.QRCodeResponse.FromString,
            _registered_method=True,
        )
        self.SendMessage = channel.unary_unary(
            "/whatsapp.WhatsAppService/SendMessage",
            request_serializer=whatsapp__pb2.SendRequest.SerializeToString,
            response_deserializer=whatsapp__pb2.SendResponse.FromString,
            _registered_method=True,
        )
        self.ListDevices = channel.unary_unary(
            "/whatsapp.WhatsAppService/ListDevices",
            request_serializer=whatsapp__pb2.Empty.SerializeToString,
            response_deserializer=whatsapp__pb2.DeviceList.FromString,
            _registered_method=True,
        )
        self.LogoutDevice = channel.unary_unary(
            "/whatsapp.WhatsAppService/LogoutDevice",
            request_serializer=whatsapp__pb2.DeviceID.SerializeToString,
            response_deserializer=whatsapp__pb2.StatusResponse.FromString,
            _registered_method=True,
        )
        self.DeleteDevice = channel.unary_unary(
            "/whatsapp.WhatsAppService/DeleteDevice",
            request_serializer=whatsapp__pb2.DeviceID.SerializeToString,
            response_deserializer=whatsapp__pb2.StatusResponse.FromString,
            _registered_method=True,
        )


class WhatsAppServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StartLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LogoutDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def DeleteDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WhatsAppServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StreamMessages": grpc.unary_stream_rpc_method_handler(
            servicer.StreamMessages,
            request_deserializer=whatsapp__pb2.Empty.FromString,
            response_serializer=whatsapp__pb2.MessageEvent.SerializeToString,
        ),
        "StartLogin": grpc.unary_unary_rpc_method_handler(
            servicer.StartLogin,
            request_deserializer=whatsapp__pb2.Empty.FromString,
            response_serializer=whatsapp__pb2.QRCodeResponse.SerializeToString,
        ),
        "SendMessage": grpc.unary_unary_rpc_method_handler(
            servicer.SendMessage,
            request_deserializer=whatsapp__pb2.SendRequest.FromString,
            response_serializer=whatsapp__pb2.SendResponse.SerializeToString,
        ),
        "ListDevices": grpc.unary_unary_rpc_method_handler(
            servicer.ListDevices,
            request_deserializer=whatsapp__pb2.Empty.FromString,
            response_serializer=whatsapp__pb2.DeviceList.SerializeToString,
        ),
        "LogoutDevice": grpc.unary_unary_rpc_method_handler(
            servicer.LogoutDevice,
            request_deserializer=whatsapp__pb2.DeviceID.FromString,
            response_serializer=whatsapp__pb2.StatusResponse.SerializeToString,
        ),
        "DeleteDevice": grpc.unary_unary_rpc_method_handler(
            servicer.DeleteDevice,
            request_deserializer=whatsapp__pb2.DeviceID.FromString,
            response_serializer=whatsapp__pb2.StatusResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "whatsapp.WhatsAppService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "whatsapp.WhatsAppService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class WhatsAppService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamMessages(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/whatsapp.WhatsAppService/StreamMessages",
            whatsapp__pb2.Empty.SerializeToString,
            whatsapp__pb2.MessageEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StartLogin(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/whatsapp.WhatsAppService/StartLogin",
            whatsapp__pb2.Empty.SerializeToString,
            whatsapp__pb2.QRCodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def SendMessage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/whatsapp.WhatsAppService/SendMessage",
            whatsapp__pb2.SendRequest.SerializeToString,
            whatsapp__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ListDevices(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/whatsapp.WhatsAppService/ListDevices",
            whatsapp__pb2.Empty.SerializeToString,
            whatsapp__pb2.DeviceList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def LogoutDevice(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/whatsapp.WhatsAppService/LogoutDevice",
            whatsapp__pb2.DeviceID.SerializeToString,
            whatsapp__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def DeleteDevice(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/whatsapp.WhatsAppService/DeleteDevice",
            whatsapp__pb2.DeviceID.SerializeToString,
            whatsapp__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
