# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: whatsapp.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor # type: ignore
from google.protobuf import descriptor_pool as _descriptor_pool # type: ignore
from google.protobuf import runtime_version as _runtime_version # type: ignore
from google.protobuf import symbol_database as _symbol_database # type: ignore
from google.protobuf.internal import builder as _builder # type: ignore

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 30, 0, "", "whatsapp.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0ewhatsapp.proto\x12\x08whatsapp"\x07\n\x05\x45mpty"y\n\x0cMessageEvent\x12\x0c\n\x04\x66rom\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04text\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\t\x12\x0e\n\x06\x62inary\x18\x06 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x07 \x01(\t".\n\x0eQRCodeResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t"[\n\x0bSendRequest\x12\n\n\x02to\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x10\n\x08\x66rom_jid\x18\x03 \x01(\t\x12\x0e\n\x06\x62inary\x18\x04 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x05 \x01(\t".\n\x0cSendResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t"\x19\n\nDeviceInfo\x12\x0b\n\x03jid\x18\x01 \x01(\t"3\n\nDeviceList\x12%\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32\x14.whatsapp.DeviceInfo"\x17\n\x08\x44\x65viceID\x12\x0b\n\x03jid\x18\x01 \x01(\t"0\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\xf7\x02\n\x0fWhatsAppService\x12;\n\x0eStreamMessages\x12\x0f.whatsapp.Empty\x1a\x16.whatsapp.MessageEvent0\x01\x12\x37\n\nStartLogin\x12\x0f.whatsapp.Empty\x1a\x18.whatsapp.QRCodeResponse\x12<\n\x0bSendMessage\x12\x15.whatsapp.SendRequest\x1a\x16.whatsapp.SendResponse\x12\x34\n\x0bListDevices\x12\x0f.whatsapp.Empty\x1a\x14.whatsapp.DeviceList\x12<\n\x0cLogoutDevice\x12\x12.whatsapp.DeviceID\x1a\x18.whatsapp.StatusResponse\x12<\n\x0c\x44\x65leteDevice\x12\x12.whatsapp.DeviceID\x1a\x18.whatsapp.StatusResponseB\tZ\x07./protob\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "whatsapp_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    _globals["DESCRIPTOR"]._loaded_options = None
    _globals["DESCRIPTOR"]._serialized_options = b"Z\007./proto"
    _globals["_EMPTY"]._serialized_start = 28
    _globals["_EMPTY"]._serialized_end = 35
    _globals["_MESSAGEEVENT"]._serialized_start = 37
    _globals["_MESSAGEEVENT"]._serialized_end = 158
    _globals["_QRCODERESPONSE"]._serialized_start = 160
    _globals["_QRCODERESPONSE"]._serialized_end = 206
    _globals["_SENDREQUEST"]._serialized_start = 208
    _globals["_SENDREQUEST"]._serialized_end = 299
    _globals["_SENDRESPONSE"]._serialized_start = 301
    _globals["_SENDRESPONSE"]._serialized_end = 347
    _globals["_DEVICEINFO"]._serialized_start = 349
    _globals["_DEVICEINFO"]._serialized_end = 374
    _globals["_DEVICELIST"]._serialized_start = 376
    _globals["_DEVICELIST"]._serialized_end = 427
    _globals["_DEVICEID"]._serialized_start = 429
    _globals["_DEVICEID"]._serialized_end = 452
    _globals["_STATUSRESPONSE"]._serialized_start = 454
    _globals["_STATUSRESPONSE"]._serialized_end = 502
    _globals["_WHATSAPPSERVICE"]._serialized_start = 505
    _globals["_WHATSAPPSERVICE"]._serialized_end = 880
# @@protoc_insertion_point(module_scope)
